baseurl = "https://example.org/"
languageCode = "en-us"
title = "Hello Friend"
theme = "hello-friend"
Copyright = "Yerzhan Sarbassov 2018"
paginate = 5

[params]
  subtitle = "A simple theme for Hugo"

# [params.logo]
#   path = "/img/your-example-logo.svg"
#   alt = "your_example_logo"

[menu]
  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/portfolio"
    weight = 100
  [[menu.main]]
    identifier = "showcase"
    name = "Showcase"
    url = "/showcase"
    weight = 200
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 300